language: java
branches:
  only:
  - develop
  - master
  - /release.*/
env:
  global:
  - secure: e0qyWi1rKOeHC0Lv9hHheZAefzX+9ih7k2R7bghkWzXrdTU1369K5t1mWZMN4jB17c+vI5b7IvLtQmhdmKY/G0bKDj26pRMVHxivTimPsFxjsX/qk8AAzJO5GPzesSKnGvzuop6EfM86kLJrs0CyW4cPxVkDAcvV8FnApVjLyGg=
  - secure: IKQO6y8rYlKUia7Pe2WLSNYuQ+z2a70fHcgMZh2o6vNcptAcfOR64hbCqCkwSGCzWH4MTYkkKNvb03hU6u34kETV0mkNRavmZuqi+9qKT0haLDt6WoJM9/Y8+oL+pg34y1AVstt1/t0Sz1LV1oxDKbYfzFCbiKO9TSRZMkVgpI4=
  - secure: djG18bOMOwAFk8nv13/56bI+S4F4bSf/K/A2nr1lywR509bVt4acXRgD8bgoPnqo+2Bf6eDNVowYINivOtTxzX1KPKIrxk8tdNTRecXZMfqPatEmEIpMlPkFHT2OoiXtYOzFwMBmFLWgHUrJdPz4x4q2uj4yxx89Pg4EZagjhE4=
  - secure: Y2nBM5O0gIAQbEovm/BRv5OZiOOYPY4wxZ9HDKky3Am7fJKHKUhQTo+LCgVK8oYcnBeQUzhJ2nAmib0Os4h8FLaANjW2DTVsvZ+rm4OgH1cdFqF061luD+dJcKozVgXYHRamAJmZMKzPSJ1vIn5Q1WDCPV22Z6e66UjvR+jBXrA=
  - secure: bORJmf6/+JUzu8GOZkNmF0GNnOd9nph1ctjzbDEX8Ubd6L0QQq/B8WgJ3uRG6UEziGfTO75e778F4Z9decI3h6pIkmjP/3nQOhUGyFB6fBcMZx4braMJ/+Ln6DZWseI7H8M33rZocmdU3OF6Ehal15ExVzaT2Ioise0oGNnE9OQ=
  - secure: icobgaeCAxD6xizcLr6o5pfhsNOCpInqlyYHBokHJ4ZHYHpHkpcshTGLs21s6ouVp8yETXzZBhLz5LnM7T9cLPjORJ2ju+fd/PooxCqW2hnbCFlyCaIdOxTBfBwO7PbgPp8qLECITx98uHh4RhOjPwba2Nexb5EbTZCwRNb3Zg0=
stages:
- name: Unit Tests
  if: branch = develop
- name: Staging
  if: branch =~ ^release
- name: Master
  if: branch = master
jobs:
  include:
  - stage: Unit Tests
    install: mvn --settings settings.xml -DskipTests=true -Dmaven.javadoc.skip=true
      -Pdevelop -B -V install
    script: mvn --settings settings.xml -Pdevelop clean test
  - stage: Staging
    install: mvn --settings settings.xml -DskipTests=true -Dmaven.javadoc.skip=true
      -Pstaging -B -V install
    script: mvn --settings settings.xml -Dmaven.javadoc.skip=true -Pstaging -B -V
      clean test
    after_success: bash ./deploy.sh
  - stage: Master
    install: mvn --settings settings.xml -DskipTests=true -Dmaven.javadoc.skip=true
      -B -V install
    script: mvn --settings settings.xml clean test site
