language: java
branches:
    only:
        - develop
        - master
before_install:
    - pushd ~/
    - curl -O http://www.anc.org/tools/settings.xml
    - popd
script:
    - mvn clean test --settings ~/settings.xml